### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by 0xAF**
Hello Daniel.

This PR will:
1. fix a bug in last character in the command buffer
2. ease the problem with the flickering, but will not fix it fully.
3. add handling for some new keys
4. rework a bit the logic around the command buffer.
5. add Disconnect method to disconnect the telnet client.

Please review the changes and we can discuss them here in the PR.
I've prepared the PR in separate commits, so it's easier for you to review.

### CODE REVIEW

**Comment by 0xAF** [comment]
Hi Daniel.
I just saw that I've mixed my coding style into yours.
I hope you have something to tidy the code automatically.
Sorry for that. My IDE (VSCode) is changing the style of the changed lines to my style.

**Review by dani007200964 — COMMENTED** [review]
Thank you for your work, it looks awesome! I have a few notes:
* Checking the buffer size is way easier now.
* The extra keys are awsome 👍 .
* The new logic for the redrawLine() function seems to work well, it's awsome. I also investigated the flickering problem, and I think it can be optimised a bit more 🛠️ . Also it network related as well.
* The ESP related things has to be guarded with the SHELLMINATOR_USE_WIFI_CLIENT define. Not a big deal, but it will fail on non ESP boards at the unit test.

I will spend this day to merge things together. I also add my optimisations to the code( it just extends your idea ). After that I think I will work on the browser based X-term solution. If that's finished I will test it intensivley and create a new release. I hope it will be done in this month.

If it's a problem for you and you need the new release with your modifications ASAP I think I can reorganise things and leave the X-term version for the future.

**Comment by dani007200964** [comment]
> Hi Daniel. I just saw that I've mixed my coding style into yours. I hope you have something to tidy the code automatically. Sorry for that. My IDE (VSCode) is changing the style of the changed lines to my style.

Not a problem, everyone has a coding style, it's a good thing :grinning:
If it's not a problem for you I will cnage it to mine, to fit in the whole project.

**Comment by 0xAF** [comment]
> Not a problem, everyone has a coding style, it's a good thing grinning If it's not a problem for you I will cnage it to mine, to fit in the whole project.

Of course, you should change it to yours to be in sync with the rest of the code. I just apologized, that I missed to do so.

**Comment by dani007200964** [comment]
I have good news!

Your modifications are worked, I have tested them.
1. It had a bug with the redrawing, but I have fixed it. It overaddressed the buffer, when it was full( number of characters in the buffer was equal with the SHELLMINATOR_BUFF_LEN define ), and I wanted to add a character in the middle of the command. It was a problem with my old version as well, bud I did not found this bug unti now.
2. The new shortcut keyes are awsome, thanks for the suggestion and the implementation. I think I will add an override option for them as well in the future.
3. I have optimised a bit your redraw algorythm, now it does not require to redraw the banner. And the cursor position setting at the end now uses calculated position instead the old ugly for loop.
4. Also with the ESP32 and ESP8266, the device has enough RAM for a sender buffer. The redraw function now creates an assembled message and send it in one piece.

You can find the working prototype in the dev branch in this commit: e0c2bc3d800433e2d740e1a64513014de665aa2e
I had to modify the example as well, because the WiFi power save mode has to be turned off, to accelerate the client handling.

__Thank you for your help!__ I hope you can use the library for something useful! 😄

**Comment by 0xAF** [comment]
Great! Thanks.
I've took a brief look into your commits.

> 1. It had a bug with the redrawing, but I have fixed it. It overaddressed the buffer, when it was full( number of characters in the buffer was equal with the SHELLMINATOR_BUFF_LEN define ), and I wanted to add a character in the middle of the command. It was a problem with my old version as well, bud I did not found this bug unti now.

I saw that, but after reworking the logic a bit, I did not manage to reproduce it. I'm glad you've fixed it for real.

> 2. The new shortcut keyes are awsome, thanks for the suggestion and the implementation. I think I will add an override option for them as well in the future.

I'll share an idea with you.
Since I'm a linux user, since early 90s, I'm quite used to a lot of linux tools and have habits about many things.
One of them is the BASH shell, which is using "readline" library internally to handle the input.
I've made some tools back in the years with libreadline and I'm somewhat familiar with it.
One of the features of readline is a simple input configuration file, called "inputrc".
You can see [here](https://www.linuxfromscratch.org/blfs/view/5.1/postlfs/inputrc.html) what it looks like.
You will notice the Home/End/PgUp/PgDown escape codes there and the "interrnal command" of readline they will execute.
On many linux systems the defaults for PgUp and PgDown is this:
```
"\e[5~": beginning-of-history
"\e[6~": end-of-history
```
Which will "scroll" to the beginning or the end of the history buffer.
This is not very useful in most cases.
So in many linux distributions there will be 2 commented lines, to replace the default for PgUp/PgDown:
```
"\e[5~": history-search-backward
"\e[6~": history-search-forward
```
What this does is to search in the history buffer, based on the first characters you've written on the prompt.

Let's say you have these commands in the history:
`this -is -a -long -command -with -arguments`
`that -was -a -long -command`

Once you start typing on the prompt the letters `th`, then hit PgUp, it will call the last command in the history, which starts with `th` (in this case `that -was....`), pressing PgUp again will call the `this -is....` command from history. No matter how many commands are in between there in the history, it will search only for commands starting with `th`.

If you have an empty prompt and did not type any characters, the PgUp and PgDown behaves like the arrow keys, because there is no search pattern and it will find every command in the history matching the no-search-pattern (meaning all commands).

This behavior is very helpful when you're working with the shell and have a history for 1000's commands.


Another search "hot-key" for the readline is CTRL-R, which when pressed will change the prompt to something like `(reverse-i-search): ` and will search the history for whatever you start typing. But will not try only in the beginning of the command, this one will search in the whole command string, not only in the start of the buffer.

[here is a demo how these hotkeys work in the shell](https://asciinema.org/a/uXPWTrVeUn9rwPEqSgmQwcmmg)


> 3. I have optimised a bit your redraw algorythm, now it does not require to redraw the banner. And the cursor position setting at the end now uses calculated position instead the old ugly for loop.
> 
> 4. Also with the ESP32 and ESP8266, the device has enough RAM for a sender buffer. The redraw function now creates an assembled message and send it in one piece.

Looks great. I like the idea of the virtual buffer and print the result once it's prepared.
I was thinking to help you implement something like that in the future, but it seems you already had the idea.

Just one more note.
The Shellminator prompt is currently `shell:~$ `. This `:~$` in the end is misleading.
It looks like you're in your home directory `~`, and misleads the user to believe there is a directory structure.

I would suggest to replace the prompt like this: `shell # ` or `shell $ `.
And for the todo list, I would suggest to implement some kind of directory structure, which is basically pointless, but something like command hierarchy is more useful.
Something like the Cisco router shells or Mikrotik shells.
Let's say you have one `ip` command, which does nothing without the correct parameters (or sub-commands).
like:
```
ip address
ip link
ip route
```
and imagine that `ip address` has a sub-commands by itself, like:
```
ip address add ...
ip address del ...
ip address show ...
# and ip route has subcommands too
ip route list ...
ip route flush ...
ip route add ...
ip route del ...
```

now, we can have an extension for the shell prompt indicating the command we are in...
so the banner will be something similar to what it is now `shell:[what] $`.
I'll try to show with this example what I mean.
```
shell:/ $
shell:/ $ ip route list
Print listing of routes here...

shell:/ $
shell:/ $ ip
shell:/ip $ help
Available commands:
address
route
link
shell:/ip $ route list
Print listing of routes here...

shell:/ip $
shell:/ip $ route 
shell:/ip/route $ list
Print listing of routes here...

shell:/ip/route $
shell:/ip/route $ /
shell:/ $

```

But that I would guess has to be implemented in the Commander-API library and just connect the resulting "extension" to the prompt banner.


Thanks for the great work.

**Comment by dani007200964** [comment]
### These are very good ideas, thansk!

I think the search features can be implemented, fairly easy, but I should note that, this library designed to work on low power devices as well. The whole library started as a terminal interface( and command parser with Commander-API ) for low power devices like AVRs, or smaller STM32s. I made it for my cocktail machine, then my friends asked me to create a library from this thing, because they needed a thing like this, mostly for robot projects. This is how it become a thing. It was 4 years ago, since then a lot has changed. I would like to keep the core functionality available for low power devices as well.

I think I will add some defines in the Shellminator-Settings.hpp to enable these advanced tunctions on the beafier devices.
If I set the history size to 50, it won't fit on any AVR for example. But if yo have a history size of 5, the whole search thing is pointless.

On the other hand, with the ESP32, STM32-F7 or the RP-2040, we have enough memory for an advanced terminal, and these features would be awsome on them.

The sub-command solution can be done fairly easily, I have done some similar things. But I think it can not be automated.
My solution was to create multiple Commander objects, with different API-tree, and every time when I switched into a subcommand section I changed the banner thext, and the Commander object for the shell. It was in early stages, I have to add some functions to do that in this version, but totally doable.

> I would suggest to replace the prompt like this: shell # or shell $ . I agree, it will be configureable as well, and it can be good for the sub-commands as well.

>

**Pull request merged**
